### ISSUE TITLE
problems for using direct solver

### ISSUE THREAD

**Issue by bzhangcw** [ralna/GALAHAD#326] opened 2024-10-02 04:50 UTC
Hi,

I hope to use GALAHAD ARC to solve cutest problems in julia. I tried the indirect solver (using CG) and it works well. Using factorization to solve the subproblems seem to cause some issues.

I implemented as follows

```julia

using GALAHAD
using Test
using Printf
using Accessors
using CUTEst
using NLPModels
using LinearAlgebra

function test_arc_direct(nlp; tol=1e-5)

  x0 = nlp.meta.x0
  hrow = nlp.hrows
  hcol = nlp.hcols
  hval = NLPModels.hess_coord(nlp, x0)

  # Objective function
  function fun(n::Int, x::Vector{Float64}, f::Ref{Float64}, userdata::userdata_arc)
    p = userdata.p
    f[] = NLPModels.obj(nlp, x)
    return 0
  end

  # Gradient of the objective
  function grad(n::Int, x::Vector{Float64}, g::Vector{Float64}, userdata::userdata_arc)
    p = userdata.p
    g .= NLPModels.grad(nlp, x)
    return 0
  end

  # Dense Hessian
  # Hessian of the objective
  function hess(n::Int, ne::Int, x::Vector{Float64}, hval::Vector{Float64},
    userdata::userdata_arc)
    hval = NLPModels.hess_coord!(nlp, x, hval)
    # println(hval)
    return 0
  end

  # Derived types
  data = Ref{Ptr{Cvoid}}()
  inform = Ref{arc_inform_type{Float64}}()
  control = Ref{arc_control_type{Float64}}()
  # Set user data
  userdata = userdata_arc(4.0)

  # Set problem data
  n = nlp.meta.nvar # dimension
  ne = nlp.meta.nnzh # Hesssian elements

  # Set storage
  g = zeros(Float64, n) # gradient
  st = ' '
  status = Ref{Cint}()

  @printf(" Fortran sparse matrix indexing\n\n")
  @printf(" tests reverse-communication options\n\n")

  # reverse-communication input/output
  eval_status = Ref{Cint}()
  f = Ref{Float64}(0.0)
  u = zeros(Float64, n)
  v = zeros(Float64, n)


  # Initialize ARC
  arc_initialize(data, control, status)

  # Set user-defined control options
  @reset control[].f_indexing = true # Fortran sparse matrix indexing
  @reset control[].maxit = Cint(10000)
  @reset control[].cpu_time_limit = Cdouble(3600)
  @reset control[].print_level = Cint(4)
  @reset control[].subproblem_direct = true
  @reset control[].hessian_available = true
  @reset control[].stop_g_absolute = Cdouble(tol)
  @reset control[].stop_g_relative = Cdouble(tol / norm(NLPModels.grad(nlp, x0)))

  # Start from 1.5
  x = copy(nlp.meta.x0)


  # access by products

  st = 'C'
  arc_import(control, data, status, n, "coordinate",
    ne, hcol, hrow, C_NULL)

  while true # reverse-communication loop
    arc_solve_reverse_with_mat(data, status, eval_status, n, x,
      f[], g, ne, hval, u, v)

    # println(status[])
    if status[] <= 0
      break
    elseif status[] == 2 # evaluate f
      eval_status[] = fun(n, x, f, userdata)
    elseif status[] == 3 # evaluate g
      eval_status[] = grad(n, x, g, userdata)
    elseif status[] == 4 # evaluate H
      eval_status[] = hess(n, ne, x, hval, userdata)
    elseif status[] == 5 # evaluate H
      eval_status[] = hessprod(n, x, u, v, false, userdata)
    elseif status[] == 6 # evaluate the product with P
      @printf(" the product with P is not defined\n")
      eval_status[] = 0
    else
      @printf(" the value %1i of status should not occur\n", status)
    end

  end


  arc_information(data, inform, status)

  if inform[].status[] == 0
    @printf("%c:%6i iterations. Optimal objective value = %5.2f status = %1i\n", st,
      inform[].iter, inform[].obj, inform[].status)
  else
    @printf("%c: ARC_solve exit status = %1i\n", st, inform[].status)
  end

  k = inform[].iter
  fx = inform[].obj
  gn = norm(g)
  t = inform[].time.total
  # Delete internal workspace
  arc_terminate(data, control, inform)
  return k, x, fx, gn, t
end

f = "EXTROSNB"
pc = "N=10"
nlp = CUTEstModel(f, "-param", pc)
name = "$(nlp.meta.name)-$(nlp.meta.nvar)"

# k, x, fx, gn, t = test_arc(nlp; tol=1e-4)
k, x, fx, gn, t = test_arc_direct(nlp; tol=1e-4)

finalize(nlp)
```

This produces the error 
```bash
julia> include("./test.jl")
 Fortran sparse matrix indexing

 tests reverse-communication options

  Problem:  (n = 10): ARC stopping tolerance = 1.0000E-04

        (a=accept r=reject n=-ve curvature h=hard case)
    It           f        grad     ratio   weight  step   # fact        time
     0      3.6040E+03 3.51E+03          1.0E+02
 Computing preconditioner

 Error return from RQS, status = -10

  Problem:  (n = 10): ARC stopping tolerance = 1.0000E-04
  Second-order model used
  Direct solution (solver ssids) of the regularization sub-problem
  Diagonal regularization used
  Number of factorization = 1, factorization time = .00 seconds
  Max entries in factors = 0
  Total time = .06 seconds


 Error return from ARC_solve -
   the factorization failed
 
C: ARC_solve exit status = -10
```

----- 
I then looked into the RQS package, but the error code -10 seems to be meaningless in this case. For convenience, I attached the project file `Project.toml`

```julia
[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GALAHAD = "c591611e-c43e-4808-98fb-ce4cafe3a717"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
```

Any idea on this problem?

**Comment by nimgould** [comment] 2024-10-02 07:04
This seems to be an error resulting from the call to SPRAL's sparse linear solver ssids. I'll ask our julia expert @amontoison to have a look at the interface. In the inerim, as your problem is small, you might try changing the default linear solvers (symmetric & definite)  from ssids to sytr and potr respectively. These can be changed by setting  control[].rqs_control[].symmetric_linear_solver (and definite_linear_solver) to the strings sytr and potr (sorry, I'm not a Julia person, and may have got this syntax wrong, but my colleague will correct me!). In the longer term, if you want to solve large problems, you will need to get hold of the optional HSL and other external linear solvers.

Don't worry, we will get this working for you, the Julia parts are new and there will inevitably be teething problems!

**Comment by bzhangcw** [comment] 2024-10-02 14:18
Thanks for your reply! 😍

**Comment by amontoison** [comment] 2024-10-02 17:33
@bzhangcw 
The issue is that we need to define two environnement variables for SPRAL's sparse linear solver SSIDS.
It's a bit annoying, particularly on Windows, but we can't avoid it for this direct solver.
```shell
export OMP_CANCELLATION=TRUE
export OMP_PROC_BIND=TRUE
```
```
  Problem:  (n = 10): ARC stopping tolerance = 1.0000E-04
  Second-order model used
  Direct solution (solver ssids) of the regularization sub-problem
  Diagonal regularization used
  Number of factorization = 1843, factorization time = .07 seconds
  Max entries in factors = 55
  Total time = .27 seconds

C:   479 iterations. Optimal objective value =  0.00 status = 0
(479, [0.9999470022085529, 0.9998937422205466, 0.9997873632054224, 0.9995747053023571, 0.9991495581083959, 0.9982998219555796, 0.9966025224463859, 0.9932165684375591, 0.9864790892918128, 0.9731407536449174], 2.8243280551010422e-9, 9.760757019314341e-5, 0.25953865f0)
```
To not have this issue, you can use dense linear solvers with LAPACK routines:
```julia
@reset control[].rqs_control.symmetric_linear_solver = galahad_linear_solver("sytr")
@reset control[].rqs_control.definite_linear_solver = galahad_linear_solver("potr")
```
```
  Problem:  (n = 10): ARC stopping tolerance = 1.0000E-04
  Second-order model used
  Direct solution (solver potr) of the regularization sub-problem
  Diagonal regularization used
  Number of factorization = 1842, factorization time = .03 seconds
  Max entries in factors = 55
  Total time = .22 seconds
```
The sparse linear solver MUMPS is also available and is recommended for large problems:
```julia
@reset control[].rqs_control.symmetric_linear_solver = galahad_linear_solver("mumps")
@reset control[].rqs_control.definite_linear_solver = galahad_linear_solver("mumps")
```
```
  Problem:  (n = 10): ARC stopping tolerance = 1.0000E-04
  Second-order model used
  Direct solution (solver mumps) of the regularization sub-problem
  Diagonal regularization used
  Number of factorization = 1843, factorization time = .06 seconds
  Max entries in factors = 55
  Total time = .25 seconds
```

**Comment by amontoison** [comment] 2024-10-02 17:40
@nimgould For HSL linear solvers, we still need a new release of `libHSL` and `HSL_jll.jl`.
If `hsl_subset` is included in the next release of `HSL_jll.jl`, we could make the same modification as above to use it.
It's quite user-friendly for the Julia users.

**Comment by nimgould** [comment] 2024-10-02 18:20
Thanks very much @amontoison. We need to document this.

I will lean on the HSL folks @jfowkes , @AndrewLister-STFC @tyronerees   to get the libHSL update as a priority.

Going forward ...

1. We can check environment variables are set using fortrans get_environment_variable.
But, as yet, fortran does not allow us to set them.However C does, and I have found a C(bind) open-source fortran code that uses C to set them. We should investigate.

2. We rely on default values for linear solvers. But really we should allow a "select" option that takes a list of potential solvers in order of quality, and pick the first that is available, by some means.

Let's think about both of these, with some urgency. @jfowkes you might also have ideas.

**Comment by bzhangcw** [comment] 2024-10-03 02:11
@nimgould @amontoison Nick and Alexis, thanks for your quick response.  I use these options, and it works perfectly (it seems MUMPS also needs this)

```
export OMP_CANCELLATION=TRUE
export OMP_PROC_BIND=TRUE
```

I will let you close this issue whenever proper.

**Comment by jfowkes** [comment] 2024-10-03 07:59
@nimgould I suggest a very simple bind(C) routine that sets `OMP_CANCELLATION` and `OMP_PROC_BIND`.

I am no longer working on HSL, so please pass the libHSL update request over to @AndrewLister-STFC.

**Comment by amontoison** [comment] 2024-10-03 13:47
@jfowkes @nimgould I think that we need to set the environment variables before that the library is dlopen'ed, which is too late if we do that from GALAHAD.

**Comment by nimgould** [comment] 2024-10-03 13:52
OK. What a shame that openmp doesn't provide system calls to allow this.  Let's close this. But I still wonder how mumps works under pure (non-mingw) windows.

**Comment by nimgould** [comment] 2024-10-03 13:52
Closing as resolved (for the time being!)

**Closed by nimgould** 2024-10-03 13:52 UTC

**Comment by nimgould** [comment] 2024-10-03 13:55
Actually, I suppose we could always check the variable is set (as this is standard fortran)
and stop with an error message if it isn't. That would at least warn users.

**Comment by amontoison** [comment] 2024-10-03 13:58
Yes, we can do that. It's what we already do when we use SPRAL in the Julia interface of Ipopt, Ipopt.jl.

**Comment by nimgould** [comment] 2024-10-03 14:02
OK, I will do that. It only needs to happen in one place (in sls_initialize).
